#ifndef __ERROR_CODE_H_
#define __ERROR_CODE_H_

enum j2735_error_code_enum
{
	SUCCESS = 0,
	FAIL,
	UNEXPECT_FAIL,
	DECODE_ERROR,
	ENCODE_ERROR,
	ASN_SEQUENCE_ADD_ERROR,
	REQUIRED_FIELD_EMPTY,
	INPUT_NULL,
	ELEMENT_OUT_OF_RANGE,
	MEMORY_ALLOCATE_FAIL
};

#endif  /* __ERROR_CODE_H_ */

